#!/bin/bash

export HOME=/root
export OLD=$PATH
export PATH=$PATH:.

composer install --dev
rm -rf dist
phing rebuild


chmod 777 vendor/neuralys/sonar-runner/bin/sonar-runner
vendor/neuralys/sonar-runner/bin/sonar-runner

phing run

export PATH=$OLD
export OLD=
